---
 homebrew_taps:
   - caskroom/versions
   - homebrew/versions
   - homebrew/binary
   - caskroom/cask
   - neovim/neovim

 homebrew_packages:
  - { name: brew-cask }
  - { name: reattach-to-user-namespace }
  - { name: git }
  - { name: exercism }
  - { name: elixir }
  - { name: tig }
  - { name: ctags-exuberant }
  - { name: fish }
  - { name: tmux }
  - { name: tree }
  - { name: golang }
  - { name: nodejs } 
  - { name: python }
  - { name: pstree }
  - { name: fish }
  - { name: youtube-dl }
  - { name: direnv }
  - { name: ack }
  - { name: coreutils }
  - { name: nmap }
  - { name: neovim }  
  - { name: vim }
  - { name: docker } 
  - { name: docker-compose }
  - { name: docker-machine }
  - { name: docker-swarm }
  - { name: ntfs-3g }  
  - { name: wget,
      install_options: enable-iri }
